### ISSUE TITLE
Adding a user permission via SDK can cause issues

### ISSUE THREAD

**Issue by lmperry** [flywheel-io/core#1143]
If that user does not exist in the system it will cause the app to throw the following:

```
2018-04-13 16:50:16      scitran.api                  base.py   375:ERRO Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "./api/handlers/containerhandler.py", line 365, in get_all
    modified_results = self.join_user_info(modified_results)
  File "./api/handlers/containerhandler.py", line 207, in join_user_info
    user = users[uid]
KeyError: u'imperry@stanford.edu'
 request_id=339cbf24-1523638216
```

This causes the UI not to load with a 'server error occurred' message. 

Suggest that the endpoint validate that the user exists and reject the request if not. 

cc: @ehlertjd

**Comment by nagem** [comment]
@lmperry do we need to do any cleanup of the db for removing users that aren't currently in the system or do you think preventing it in the future will be enough?
