### ISSUE TITLE
Cannot update info fields with a blank key

### ISSUE THREAD

**Issue by ehlertjd** [flywheel-io/core#1249]
Setting a blank key on file info is permitted when doing an info **replace**
i.e.
```python
    r = as_admin.post('/projects/' + project + '/info', json={
        'replace': {
            '': 'no-key'    
        }
    })
```

However trying to change the value via **set** results in a 500 error from the server:
```python
    r = as_admin.post('/projects/' + project + '/info', json={
        'set': {
            '': 'new-value'    
        }
    })
```

Error:
```
2018-06-08 17:53:19      scitran.api                  base.py   393:ERRO Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "./api/handlers/containerhandler.py", line 458, in modify_info
    self.storage.modify_info(_id, payload, modify_subject=modify_subject)
  File "./api/dao/basecontainerstorage.py", line 394, in modify_info
    return self.dbc.update_one(query, update)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 835, in update_one
    bypass_doc_val=bypass_document_validation)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 710, in _update
    _check_write_command_response([(0, result)])
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 301, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
WriteError: The update path 'info.' contains an empty field name, which is not allowed.
```

**Comment by ehlertjd** [comment]
Added a test-case in commit 3f31891ba9f70b6b993db1bdce3a784fae2e2cca
