### ISSUE TITLE
Getting certain sessions as root results in 500

### ISSUE THREAD

**Issue by ehlertjd** [flywheel-io/core#1306]
Reproduced on dev instance.

```
uwsgi_1           | 2018-07-24 14:55:25      scitran.api                  base.py   407:DEBU from justinehlert@flywheel.io GET /api/sessions/576be45459b2b6346719ed7c {u'root': u'true'} request_id=d706330c-1532444125 origin=user:justinehlert@flywheel.io
uwsgi_1           | 2018-07-24 14:55:25      scitran.api                  base.py   401:ERRO 'NoneType' object has no attribute '__getitem__' request_id=d706330c-1532444125 origin=user:justinehlert@flywheel.io
uwsgi_1           | Traceback (most recent call last):
uwsgi_1           |   File "/var/scitran/code/api/api/web/base.py", line 399, in log_user_access
uwsgi_1           |     filename=filename, multifile=multifile, origin=origin, download_ticket=ticket)
uwsgi_1           |   File "/var/scitran/code/api/api/access_log.py", line 43, in log_user_access
uwsgi_1           |     tree = get_parent_tree(cont_name, cont_id)
uwsgi_1           |   File "/var/scitran/code/api/api/dao/hierarchy.py", line 129, in get_parent_tree
uwsgi_1           |     group_id = project['group']
uwsgi_1           | TypeError: 'NoneType' object has no attribute '__getitem__'
uwsgi_1           | 2018-07-24 14:55:25      scitran.api                  base.py   419:WARN justinehlert@flywheel.io 500 Unable to log access. request_id=d706330c-1532444125 origin=user:justinehlert@flywheel.io
uwsgi_1           | 2018-07-24 14:55:25      scitran.api                  base.py   386:ERRO Traceback (most recent call last):
uwsgi_1           |   File "/usr/lib/python2.7/site-packages/webapp2.py", line 570, in dispatch
uwsgi_1           |     return method(*args, **kwargs)
uwsgi_1           |   File "/var/scitran/code/api/api/web/request.py", line 56, in log_user_access_from_request
uwsgi_1           |     self.log_user_access(access_type, cont_name=cont_name, cont_id=cont_id, filename=filename)
uwsgi_1           |   File "/var/scitran/code/api/api/web/base.py", line 402, in log_user_access
uwsgi_1           |     self.abort(500, 'Unable to log access.')
uwsgi_1           |   File "/var/scitran/code/api/api/web/base.py", line 420, in abort
uwsgi_1           |     webapp2.abort(code, detail=detail, **kwargs)
uwsgi_1           |   File "/usr/lib/python2.7/site-packages/webapp2.py", line 1830, in abort
uwsgi_1           |     raise cls(*args, **kwargs)
uwsgi_1           | HTTPInternalServerError: Unable to log access.
uwsgi_1           |  request_id=d706330c-1532444125 origin=user:justinehlert@flywheel.io
```

**Comment by ehlertjd** [comment]
Also happens with some acquisitions

**Comment by nagem** [comment]
This error is from the "orphaned" sessions on dev. They were orphaned via the old bug that would allow you to hide all sessions in a project and then delete the project.  I would consider the goal of this ticket:

  1. Create a plan for how to handle orphaned containers on production sites
  2. Clean up/handle orphaned containers via a db update.

**Comment by hkethi002** [comment]
We could move them all to a new project in the unknown group and save the old project_id/label in the session info field. 
Although we could also create a new project for each group that has orphaned sessions using the group field on sessions.

**Comment by nagem** [comment]
Since the user deleted the project, I'm not sure these sessions are wanted in the system. I'd suggest we go with whatever will allow the user to easily delete them properly.

**Comment by nagem** [comment]
They already cannot be accessed individually via the API, maybe just removing them is the best option?

**Comment by hkethi002** [comment]
I thought about that, but I think that since the user hid them, there's a chance that they expected to be able to unhide them later on, although I agree that if a user orphaned the sessions, they were probably trying to delete them. If we do decide to remove them, we should make sure that the user that hid the data would've been able to delete them.
