### ISSUE TITLE
Matlab SDK error when URL includes spaces

### ISSUE THREAD

**Issue by lmperry** [flywheel-io/core#1514]
When using methods that access certain resources (e.g., filenames) with spaces in them an error occurs as a result of the spaces in the url not being properly handled: 

```
fw.getAcquisitionFileInfo(acquisition_id, '02 T1w 1mm sag_dicom.zip');
Error using flywheel.ApiClient/callApi (line 31)
Java exception occurred:
java.lang.RuntimeException: Unable to construct method
at io.flywheel.rest.RestUtils.createMethod(RestUtils.java:61)
at io.flywheel.rest.RestClient.callApi(RestClient.java:140)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedConstructorAccessor80.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at io.flywheel.rest.RestUtils.createMethod(RestUtils.java:58)
... 1 more
Caused by: java.lang.IllegalArgumentException: Invalid uri
'https://stanfordlabs.flywheel.io:443/api/acquisitions/5703003f7bc0d4db92dd28d4/files/02 T1w 1mm sag_dicom.zip/info':
escaped absolute path not valid
at org.apache.commons.httpclient.HttpMethodBase.<init>(HttpMethodBase.java:222)
at org.apache.commons.httpclient.methods.GetMethod.<init>(GetMethod.java:89)
... 5 more

Error in flywheel.api.AcquisitionsApi/getAcquisitionFileInfo (line 1501)
            resp = obj.apiClient.callApi('GET', '/acquisitions/{AcquisitionId}/files/{FileName}/info', ...

Error in flywheel.Flywheel/getAcquisitionFileInfo (line 584)
            [returnData, resp] = obj.acquisitionsApi.getAcquisitionFileInfo(varargin{:});
 
```

I'm guessing the solution is to replace spaces with `%20` when building the URL in [buildURL](https://github.com/flywheel-io/core/blob/master/sdk/codegen/src/main/resources/matlab/flywheel_private_methods.mustache#L73-L75).

**Comment by ehlertjd** [comment]
Closed via #1518
